[theme]

# Primary accent color for interactive elements.
primaryColor = "#08306b"

# Background color for the main content area.
backgroundColor = "#fffaf6"

# Background color used for the sidebar.
secondaryBackgroundColor = "#969696"

# Color used for almost all text.
textColor = "#252525"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "monospace"

[server]
runOnSave = true